<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <RootNamespace>Store.Model</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
<!--   <ItemGroup>
    <Using Include="Microsoft.Extensions.DependencyInjection"/>
    <Using Include="Microsoft.Extensions.Configuration"/>
  </ItemGroup> -->
</Project>